print("Division produces a float :")
print("3/4 gives")
print(3/4)
print("Exact division also produces a float :")
print("16/4 gives")
print(16/4)
print("Addition with a float produces a float :")
print("6+.5 gives")
print(6+.5)
print("Number without a point is an integer :")
print("15 gives")
print(15)
print("Number with a point is a float :")
print("15.5 gives")
print(15.5)
print("15. gives")
print(15.)
print("Numbers can be converted to float or integers :")
print("int(15.5) gives")
print(int(15.5))
print("float(15) gives")
print(float(15))
