print("Quizz - Electricity")
print((23+32+64) / 3)
print("===========================================")
print("")
print("")
print("Quizz - Floor tiles")
print("Tiles needed :")
print((9*7)+(5*7))
print("Tiles left over with 17 packages :")
print((17 * 6) - ((9*7)+(5*7)))
print("===========================================")
